ALTER TABLE AuthorTag
DROP CONSTRAINT FK_AuthorTag_Author;

ALTER TABLE AuthorTag
ADD CONSTRAINT FK_AuthorTag_Author
FOREIGN KEY (AuthorId)
REFERENCES Author(Id)
ON DELETE CASCADE;

ALTER TABLE AuthorTag
DROP CONSTRAINT FK_AuthorTag_Tag;

ALTER TABLE AuthorTag
ADD CONSTRAINT FK_AuthorTag_Tag
FOREIGN KEY (TagId)
REFERENCES Tag(Id)
ON DELETE CASCADE;