ALTER TABLE BlogTag
DROP CONSTRAINT FK_BlogTag_Blog;

ALTER TABLE BlogTag
ADD CONSTRAINT FK_BlogTag_Blog
FOREIGN KEY (BlogId)
REFERENCES Blog(Id)
ON DELETE CASCADE;

ALTER TABLE BlogTag
DROP CONSTRAINT FK_BlogTag_Tag;

ALTER TABLE BlogTag
ADD CONSTRAINT FK_BlogTag_Tag
FOREIGN KEY (TagId)
REFERENCES Tag(Id)
ON DELETE CASCADE;